name: Android Feature Branch CI

on:
  push:
    branches-ignore:
      - master
      - release*

jobs:
  build:
    name: Gradle build pass
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleNormalDebug
      
  unittest:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew test --stacktrace

  espressotest:
    name: Instrumentation tests
    needs: build

    runs-on: macos-latest

    steps:
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.3

      - name: Run Espresso UI Tests
        uses: vgaidarji/android-github-actions/emulator@v1.0.1
        with:
          args: "./gradlew connectedCheck"
          
#  espressotest:
#    name: Run Espresso Tests
#    runs-on: macos-latest

#    steps:
#    - uses: actions/checkout@v1
#    - name: set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: Android Emulator Runner
#      uses: ReactiveCircus/android-emulator-runner@v2.6.0
#      with:
#        api-level: 23
#        #target: # optional, default is default
#        #arch: # optional, default is x86
#        #profile: # optional - Hardware profile used for creating the AVD - e.g. `Nexus 6`.
#        # command-line options used when launching the emulator - e.g. `-no-window -no-snapshot -camera-back emulated`.
#        #emulator-options: # optional, default is -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
#        # whether to disable animations - true or false
#        disable-animations: true # optional, default is true
#        # build number of a specific version of the emulator binary to use e.g. `6061023` for emulator v29.3.0.0.
#        #emulator-build: # optional
#        # custom script to run - e.g. `./gradlew connectedCheck`
#        script: ./gradlew connectedCheck
