  
name: Android Feature Branch CI
# modified from https://github.com/uber/AutoDispose/blob/master/.github/workflows/ci.yml
on:
  push:
    branches-ignore:
      - master
      - release*

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Test Suite (Unit [TODO Instrumented]) [JDK ${{ matrix.java_version }}]
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        # api-level: 29
        api-level: 23
        target: default
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedCheck --stacktrace
