name: Android Feature Branch CI
# modified from https://github.com/uber/AutoDispose/blob/master/.github/workflows/ci.yml
on:
  push:
    branches-ignore:
      - master
      - release*

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run Test Suite (Unit [TODO Instrumented]) [JDK ${{ matrix.java_version }}]
    runs-on: macos-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      # In order to have sha256sum on macOS, we need to install coreutils first
      # Use this until coreutils or sha256sum are natively included in macOS on actions https://github.com/actions/virtual-environments/issues/90
      - name: Install coreutils for macOS
        run: brew install coreutils

      - name: Checkout
        uses: actions/checkout@v1

      - name: Check Gradle checksum
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ZacSweers/check-gradle-checksums/master/check-gradle-checksums.sh)"

      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.3
      
      - name: Ensure $ANDROID_HOME is set
        run: echo $ANDROID_HOME
      
      - name: Install Packages
        run: $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-23;google_apis;x86"
      
      - name: Accept Licenses
        run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
      
      - name: Create AVD
        run: $ANDROID_HOME/tools/bin/avdmanager -v create avd -n test_device -k "system-images;android-23;google_apis;x86;no"
        
      - name: Run AVD
        run: $ANDROID_HOME/emulator/emulator test_device 

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Configure Gradle
        # Initial gradle configuration, install dependencies, etc
        run: ./gradlew help

      - name: Build Project
        run: ./gradlew assemble --stacktrace

      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
      
      - name: Run Intsrumentation Tests
        run: ./gradlew connectedTest --stacktrace

      - name: Delete AVD
        run: $ANDROID_HOME/tools/bin/avdmanager delete avd -n
      
      - name: Reclaim Memory
        run: ./gradlew --stop && jps|grep -E 'KotlinCompileDaemon|GradleDaemon'| awk '{print $1}'| xargs kill -9

      - name: Final Checks
        run: ./gradlew check --stacktrace
