name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  offlinemockapk:
    name: Generate Offline Mock Debug APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build offline mock debug APK
        run: bash ./gradlew assembleOfflinemockDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-offlinemock-debug
          path: app/build/outputs/apk/offlinemock/debug/app-offlinemock-debug.apk

      - name: Build Euro Central Bank debug APK
        run: bash ./gradlew assembleOnlineecbDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-onlineecb-debug
          path: app/build/outputs/apk/offlinemock/debug/app-onlineecb-debug.apk

      - name: Build Production debug APK
        run: bash ./gradlew assembleProductionDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-production-debug
          path: app/build/outputs/apk/offlinemock/debug/app-production-debug.apk

