name: Android Feature Branch CI

on:
  push:
    branches-ignore:
      - master
      - release*

jobs:
  unittest:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew test --stacktrace

  espressotest:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Espresso tests
        uses: vgaidarji/android-github-actions-emulator@v1.0.1