  
name: Android Feature Branch CI
# modified from https://github.com/uber/AutoDispose/blob/master/.github/workflows/ci.yml
on:
  push:
    branches-ignore:
      - master
      - release*

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run Test Suite (Unit [TODO Instrumented]) [JDK ${{ matrix.java_version }}]
    runs-on: macos-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
        - uses: actions/checkout@v1
        - uses: malinskiy/action-android/install-sdk@release/0.0.5
        - run: adb devices
        - run: echo $ANDROID_HOME
        - run: ./gradlew connectedCheck --stacktrace
