name: Android Feature Branch CI
# modified from https://github.com/uber/AutoDispose/blob/master/.github/workflows/ci.yml
on:
  push:
    branches-ignore:
      - master
      - release*

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run Test Suite (Unit [TODO Instrumented]) [JDK ${{ matrix.java_version }}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: "Run UI Tests"
        uses: vgaidarji/android-github-actions-emulator@v1.0.1
