name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  offlinemockapk:
    name: Generate Debug APKs
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Offline Mock debug APK
        run: bash ./gradlew assembleOfflinemockDebug --stacktrace

      - name: Upload Offline Mock APK
        uses: actions/upload-artifact@v1
        with:
          name: app-offlinemock-${{ github.run_number }}-debug
          path: app/build/outputs/apk/offlinemock/debug/app-offlinemock-debug.apk

      - name: Build Euro Central Bank Debug APK
        run: bash ./gradlew assembleOnlineecbDebug --stacktrace

      - name: Upload ECP APK
        uses: actions/upload-artifact@v1
        with:
          name: app-onlineecb-${{ github.run_number }}-debug
          path: app/build/outputs/apk/onlineecb/debug/app-onlineecb-debug.apk

      - name: Build Production Debug APK
        run: bash ./gradlew assembleProductionDebug --stacktrace

      - name: Upload Production APK
        uses: actions/upload-artifact@v1
        with:
          name: app-production-${{ github.run_number }}-debug
          path: app/build/outputs/apk/production/debug/app-production-debug.apk

